spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
  security:
    oauth2:
      resourceserver:
        opaque-token:
          client-id: unknown
          client-secret: unknown
          introspection-uri: unknown

keycloak:
  server-url: unknown
  realm: unknown
  client-id: unknown
  client-secret: unknown

mongock:
  enabled: false

springdoc:
  api-docs.enabled: true
